### ISSUE TITLE
The app hangs while loading specific titles.

### ISSUE THREAD

**Issue by Malkeus** [MakeYourLifeEasier/novel-ebook.com#10]
While loading certain titles, the app will hang on the dimmed out screen with loading circle. It's possible to choose a different title if you scroll down. I wasn't going to make a bug report, but it's happening on my PC and on my Android device, both using google chrome.
Titles:  Reincarnated into a hell hound
    Rebirth: modern day cultivator

There are more, but these are the two I'm having issues with today.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelGuardian** [comment]
Thanks for the bug report. It seems to be an issue with illegal characters in the url. I will add a check for broken links in the next couple of days

**Comment by Malkeus** [comment]
Thank you for creating this, it's a huge time saver.

**Comment by MichaelGuardian** [comment]
New update is live. All broken links should be removed.
