### ISSUE TITLE
Swordmeister of Rome ( chapters cramped no indentation or spasing)  

### ISSUE THREAD

**Issue by adamdante7** [MakeYourLifeEasier/novel-ebook.com#101]
Hello guys, 
So the problem strats from chapter 41 onward, where the chapters are cramped with indentation nor spacing , it's just a huge endless one chunk of paragraph. 

Could you please fix it 💕 
Thank you,  best regards 💕 

![16086562204795007806656733142685](https://user-images.githubusercontent.com/76490130/102913491-1e034c00-447f-11eb-895d-38ed0e8884ab.jpg)

**Comment by MichaelGuardian** [comment]
Should be fixed.
But generally #44
