### ISSUE TITLE
I click on chose chapter both start and end  but it doesn't show work 

### ISSUE THREAD

**Issue by adamdante7** [MakeYourLifeEasier/novel-ebook.com#103]
Choosing starting chapter and ending chapter dlfsnt work 

It works for other novels but ( stop! Friendly fire!)  This novel the chapter choosing doesn't work 
I click and nothing happens 
![16088353800757694633256280409937](https://user-images.githubusercontent.com/76490130/103103265-3d85aa80-4620-11eb-8ecb-ff7920fd6ba5.jpg)u

**Comment by MichaelGuardian** [comment]
Fixed
