### ISSUE TITLE
Lord Xue Ying not Completely

### ISSUE THREAD

**Issue by ragan337** [MakeYourLifeEasier/novel-ebook.com#106]
Lord Xue Ying chapter 239 -1050 not completely

**Comment by tomin141** [comment]
Yes I agree. And chapters 206, 212 are wrong. I'm not sure if there are more such chapters, but it certainly applies to these.
But still the novel is great so far. It is a pity it is not comlete here.

**Comment by MichaelGuardian** [comment]
Fixed

**Comment by ragan337** [comment]
Thank you
