### ISSUE TITLE
SSRF security vulnerabilty in your site.

### ISSUE THREAD

**Issue by kenjoe41** [MakeYourLifeEasier/novel-ebook.com#11]
**Describe the bug**
Your API endpoint has an SSRF security vulnerability. It can make and GET arbitrary requests to any web address. I didn't extensively test it or try to escalate it.

**To Reproduce**
1. Go to 'https://api.novel-ebook.com/get?url=google.com'
2. Change the 'google.com' to any other site and it will fetch it.

**Expected behavior**
I noticed you mostly us wuxiaworld.co, it should only fetch from whitelisted sites should it need to use multiple sources.

**How to solve it.**
Add a white list of allowed domains to make get requests to, before it makes any requests.

**Comment by MichaelGuardian** [comment]
Puh you got me scared there for a minute, but the api was open by desing as there are other web applications who use this endpoint. Requests that are not expected (e.g. google.com) are looged and compiled into a daily report that I get via E-Mail.

That being said I have to admit it's kinda risky, hotfix deployed.

Thanks for the report!
