### ISSUE TITLE
unable to download more than 5 chapters of "The Grandmaster Strategist".

### ISSUE THREAD

**Issue by oreki12** [MakeYourLifeEasier/novel-ebook.com#110]
**Describe the bug**
unable to download more than 5 chapters of "The Grandmaster Strategist".

**Expected behavior**
need all chapters of "The Grandmaster Strategist".

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : window
 - Browser [e.g. chrome, safari] : chrome

**Comment by MichaelGuardian** [comment]
Fixed
