### ISSUE TITLE
Dual cultivation error from ch 602

### ISSUE THREAD

**Issue by thisyoun** [MakeYourLifeEasier/novel-ebook.com#114]
**Describe the bug**
From chapter 602 of dual cultivation there is an error, chapter are empty

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kirune-tora** [comment]
-Still happening from chapter 602 onwards

-chapters 392 to 396 are placeholders

-there is also a gap from 589 to 596

**Comment by MichaelGuardian** [comment]
#44
