### ISSUE TITLE
Keeps loading and not getting a file for reborn at boot camp novel

### ISSUE THREAD

**Issue by humbleweeb** [MakeYourLifeEasier/novel-ebook.com#116]
**Describe the bug**
I’ve been trying to download the chapters from the novel Reborn at boot camp. But when I press download it says the it’s packing the files and it might take a while ( which is normal) but it keeps loading for hours and I get nothing.

**To Reproduce**
1. Go to 'type reborn at boot camp in the browser of the novel-evilness site'
2. Click on 'Reborn at boot camp, click on starter chapter 1 and end chapter 1051, and then click download'

**Expected behavior**
What I orgibaly thought would be the outcome is that I would get all chapters in a file that was either a zip or an epub, not to wit an hour and still get nothing.

**Comment by Night-Sign** [comment]
i also experience downloading the file but its chapters are missing from 272 Up

**Comment by MichaelGuardian** [comment]
Fixed
