### ISSUE TITLE
Incomplete chapters of Rebirth of an idle nobelwoman chapters 184-398

### ISSUE THREAD

**Issue by humbleweeb** [MakeYourLifeEasier/novel-ebook.com#117]
The chapters in the story rebirth of an idle nobelwoman are incomplet from chapters 184 to  398( only one page for each chapter). And the only wording on the chapters are these words : “ “In preparation, Keguan Please wait a moment, after the updates, you need to refresh the page to get the latest updates!

Please go to to read the latest chapters for free”

Hopefully this problem will be fixed because I’ve seen it in other stories when downloading them on your site. 

Thank you

**Comment by MichaelGuardian** [comment]
#44
