### ISSUE TITLE
Last few chapters of Divine Throne of Primordial Blood are all HTML

### ISSUE THREAD

**Issue by theonlygusti** [MakeYourLifeEasier/novel-ebook.com#12]
The last few chapters (Book 5, ...) of Divine Throne of Primordial Blood don't look like an ebook: there's no paragraph formatting etc.

Instead it's just raw HTML.

**Comment by MichaelGuardian** [comment]
The problem lies with the third party  the content is hosted on. I am reluctant to release a fix for this as it might cause problems in the future.

Thanks for the report though. If the problem gets more frequent I'll release the fix.
