### ISSUE TITLE
Bad Source for novels

### ISSUE THREAD

**Issue by Aonodensetsu** [MakeYourLifeEasier/novel-ebook.com#121]
Chapters are broken in a few books, probably because of a bad source, I would like to download the new chapters but they're empty, am asking for a fix if at all possible. (Is this the only source that the website uses? If not, why is it required, if yes, is there a way to notify the translator of this problem?)
EDIT: Seems like it's caused by Keguan, on a few novels. Does wuxiaworld have any control over it 🤔?

**Comment by MichaelGuardian** [comment]
New sources are on the roadmap, when i can find the time might add them or replace the current one.
