### ISSUE TITLE
Dual cultivation -Several chapters missing

### ISSUE THREAD

**Issue by kirune-tora** [MakeYourLifeEasier/novel-ebook.com#125]
**Describe the bug**
Dual Cultivation novel has several chapters missing:

-chapters 392 to 396 are placeholders

> "This is a test for something on webnovel. The real chapter is ready but will be posted a little bit later(Approx 30mins from now). Thank you for being patient. There will also be a second chapter today."

-there is also a gap from chapter 589 to 596
the content table doesn't even show a title, but a empty line, and the chapters are blank

-From chapter 602 onwards (715 right now) theres no content to show except for:

> In preparation, Keguan Please wait a moment, after the updates, you need to refresh the page to get the latest updates!

**To Reproduce**
1. Go to https://novel-ebook.com/#
2. Click on Dual Cultivation
3. Select first chapter as staring chapter
4. Select last chapter as ending chapter
4. Check the chapters mentioned above
5. see errors

**Expected behavior**
The chapters should be all there, and filled with content. Checked them on origin website. The content is there

**Screenshots**

![Dual Cultivation Chapter 392](https://user-images.githubusercontent.com/4953511/107860911-797c0580-6e42-11eb-9ba7-ff2696bef416.png)
![Dual Cultivation Chapter 393](https://user-images.githubusercontent.com/4953511/107861066-8816ec80-6e43-11eb-92fc-3f907549a7af.png)
![Dual Cultivation Chapter 394](https://user-images.githubusercontent.com/4953511/107861068-8b11dd00-6e43-11eb-8272-dfbfb7653015.png)
![Dual Cultivation Chapter 395](https://user-images.githubusercontent.com/4953511/107861071-8d743700-6e43-11eb-8b8e-15675718607e.png)
![Dual Cultivation Chapter 396](https://user-images.githubusercontent.com/4953511/107861072-9107be00-6e43-11eb-98a0-6aa51cb91510.png)
![Dual Cultivation Mising Chapter 590 to 595](https://user-images.githubusercontent.com/4953511/107861073-936a1800-6e43-11eb-8c81-96327ba29acb.png)
![Dual Cultivation Mising Chapter 602 onwards](https://user-images.githubusercontent.com/4953511/107861074-9533db80-6e43-11eb-8e75-5b8fa7c5a85b.png)

**Comment by MichaelGuardian** [comment]
#44
