### ISSUE TITLE
unable to load and download Fields of Gold 

### ISSUE THREAD

**Issue by WanderingVirtue21** [MakeYourLifeEasier/novel-ebook.com#126]
**Describe the bug**
Once the novel is chosen, it will only load and doesn't even display the novel information nor the download option. I tried using 2 different browsers. 

**To Reproduce**
1. Go to website novel-ebook.com
2. Scroll down and locate **_"Fields of Gold"_** or simply use the search option
4. Once you select the novel **_"Fields of Gold"_**, you will only have a loading screen. It will not route you to the novel information and download option

**Expected behavior**
Once the novel is selected, loading should only take at most 2-3 minutes since there are only less than 700 chapters

**Screenshots**
![image](https://user-images.githubusercontent.com/79087577/107940147-bd961400-6fc2-11eb-95f6-916e4093011f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Avast Secure Browser
 - Version: Firefox version 85.0.2; Avast Secure Browser Version 88.0.7980.150

**Smartphone (please complete the following information):**
 - not applicable (I did not try)

**Additional context**
I tried refreshing and restarting the browsers several times but it didn't work. On another note, I can download other novels and even see the novel information/description

**Comment by killerclown3** [comment]
I have the same problem and he told me that the servers the novels are hosted on are backed up and the request can't go through.

**Comment by MichaelGuardian** [comment]
The issue for this novel is separate. Because of copyright, this content was removed.
The entry for this novel will be deleted.

**Comment by MichaelGuardian** [comment]
Fixed
