### ISSUE TITLE
missing whitespaces and newlines, joining blocks of text back to back

### ISSUE THREAD

**Issue by GitLad** [MakeYourLifeEasier/novel-ebook.com#128]
If you use the site and search for Omniscient Reader, select 1 to 551 chapters and download it, from 50th+ chapter it has no new lines or spaces, causing blocks of texts join back to back.

Tried multiple times, happens 10 out of 10.

**Comment by MichaelGuardian** [comment]
#44 The data source has wrong formatting, can't fix.
