### ISSUE TITLE
Can't load novel information

### ISSUE THREAD

**Issue by killerclown3** [MakeYourLifeEasier/novel-ebook.com#129]
I have tried every browser and even mobile but i still can't seem to load the novel info after i click a title. Even if i choose different title it still won't load and continues to load forever. I hope this can be fixed i really love this webapp and would love to continue to use it.

**Comment by MichaelGuardian** [comment]
Sorry about that! I will investigate this issue tomorrow and try to bring the site back up asap

**Comment by MichaelGuardian** [comment]
It seems that the source site hosting all the content has big load problems at the moment. I will add a notice to the main page of the site but sadly there is not much I can do here.
