### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by inheritno** [MakeYourLifeEasier/novel-ebook.com#13]
Unprecedented Pill Refiner： Entitled Ninth Young Lady

Adorable Treasured Fox： Divine Doctor Mother Overturning The Heavens!

Ghost Emperor Wild Wife: Dandy Eldest Miss

When I click on these novels there is no popup only loading 

I am using Win10 and tested on firefox vivaldi chrome opera edge  without addones or extensions

**Comment by MichaelGuardian** [comment]
There seems to be an encoding issue. Fix should be out in the next couple of days.

**Comment by inheritno** [comment]
Now is not working at all

**Comment by MichaelGuardian** [comment]
Site should work again now.

The bug you previously discribed is still not fixed

**Comment by vinaykiran14** [comment]
Physician's Odyssey

**Comment by Shaystr94** [comment]
I am getting the infinite loading on probably all of them. I have tried some I have already downloaded,
Against the Gods, Battle Through the Heavens, Heavenly Jewel Change, Limitless Sword God, Tales of Demons and Gods, and Warlock of the Magus World. I have tried getting them on W10 Chrome, Firefox, and IE; Android Chrome.

**Comment by MichaelGuardian** [comment]
Server was down for roughly 12 hours. Everything is restarted.

**Comment by Shaystr94** [comment]
I am still having the infinite loading issue. I have tried the same books through the same methods. Is there anything you can think of that I should try, or is the server still having issues?

**Comment by MichaelGuardian** [comment]
Should be working now. The server stability will not be good for the next couple of days as a few updates to the backend are under way. Sorry for the inconvinience.

**Comment by Shaystr94** [comment]
You are doing amazing work. Thank you

**Comment by viperian** [comment]
There's infinite loading on all novels with a colon(:) and apostrophe(') on them.
Endless Path : Infinite Cosmos
The Lord's Empire
MMO: Pierce Heaven 'Til It Breaks
Reborn: Evolving From Nothing
Rebirth: The New Game of Life
MMORPG: The Elementalist
MMORPG: Martial Gamer
Just some of the one's I encountered here.

**Comment by sophiah17** [comment]
i am having the same problem but with:
Across the Stunning Beast Princess: Phoenix Against the World
Insanely Pampered Wife: Divine Doctor Fifth Young Miss

**Comment by Asterisk21** [comment]
i have the  same problem with:
the anime trope system stone vs. the viper 
endless journey infinite realms
endless path infinite cosmos

**Comment by dinenek** [comment]
Evil Emperor’s Poisonous Consort

usually all books with ":" in the title

**Comment by MichaelGuardian** [comment]
The issue has been fixed. All novels with special characters should work fine now.

**Comment by Number14th** [comment]
Hi, Michael. **Fields of Gold** has **Infinite Loop issue**, while other novels I tried are fine (Farming for Gold, Golden Hero, Golden Fox with System, etc.). I am using Desktop`s Mozilla Firefox. Hopefully this issue can be fixed soon. Thanks.

**Comment by MichaelGuardian** [comment]
Just checked it out, this novel is not available for copyright reasons. I'll add a notification later but the novel won't be available
