### ISSUE TITLE
Downloadable novel-ebook program?

### ISSUE THREAD

**Issue by killerclown3** [MakeYourLifeEasier/novel-ebook.com#130]
**Is your feature request related to a problem? Please describe.**
It isn't related to a problem more of a question whether it is possible or not. Also whether you would be willing to make such a program for the community.

**Describe the solution you'd like**
I was wondering if you could make a standalone novel-ebook kind of like your original program but with more sources. 

**Describe alternatives you've considered**
There really no alternatives beside not making it and just sticking to the webapp version.

**Additional context**
I would love it if we would be able to add additional sources easily.

**Comment by MichaelGuardian** [comment]
There is no plan on making such a program. I've created one with a different source that you can find on my github (don't think it still works though). It's not worth the effort but putting more sources is on my todo list as soon as I find some time.
