### ISSUE TITLE
chapter contend for reborn at boot camp general dont mess around have stop from chapter 272 above

### ISSUE THREAD

**Issue by Night-Sign** [MakeYourLifeEasier/novel-ebook.com#131]
**Describe the bug**

**To Reproduce**
1. Go to '...'novel ebook.com
2. Click on '....'click on the search
3. Scroll down to '....'scroll down choose the novel reborn at boot camp general dont mess around
4. See error downloaded finishe but content starting chapter 272 above is missing

**Expected behavior**
i expect that after i downloaded it the chapters are complete but then it disappoints me
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: realme 5i

**Additional context**

**Comment by MichaelGuardian** [comment]
#44
