### ISSUE TITLE
Stuck at “loading screen” for every single novel I try to open

### ISSUE THREAD

**Issue by djxjjsn** [MakeYourLifeEasier/novel-ebook.com#132]
Once I tap on the title of any book it starts loading and just keeps on loading endlessly without ever show me the window.

I’ve changed browsers on moblie from Safari to Chrome and Firefox and then tried the same on my laptop, but still got the same result.

![81BA54FA-AB46-4265-8829-5236BBD75590](https://user-images.githubusercontent.com/79859449/109522449-92c1ba80-7aae-11eb-9903-c82035b31ee5.jpeg)

**Comment by MichaelGuardian** [comment]
Thanks for reminding me, still have to put up a notice. 
Currently the source site for the novels has some load problems. Can't really do much about it sadly, maybe try it again in a couple of days

**Comment by killerclown3** [comment]
Can you tell us what sources novel-ebook.com use?

**Comment by MichaelGuardian** [comment]
Issues have been resolved
