### ISSUE TITLE
Soul land(Douluo Dalu) IV is being translated once again. Can you add this?

### ISSUE THREAD

**Issue by butterywaffles77** [MakeYourLifeEasier/novel-ebook.com#134]
https://www.novelupdates.com/series/ultimate-fighting/

This one ^

It was being translated for some time then the translators quit(?). It is back up now, and people (including myself) probably want it. Can you add this to the collection?

**Comment by MichaelGuardian** [comment]
Normally don't do novel requests but you got lucky. It should be available

**Comment by butterywaffles77** [comment]
Yooo Thanks dude! Also, is it ok for me to share this website on niche(~4k subs) subreddits? I've been refraining from doing so cause 1) I don't want your website to be  #taken down, and 2) traffic(I don't know much about this but just it case it gets overloaded if I post it on r/sololeveing or something). All the best, I know this you don't get paid much to do this. Once I get my own credit card(still in school) I'll try to support you even just by a little bit.

**Comment by MichaelGuardian** [comment]
Appreciate it! I just changed some things around on the server, so it'll take a couple of days for the most popular novels to be cached again, so performance might suffer for a couple of days.
Most subreddits don't like sharing this site though, so make sure to read the rules before posting.
