### ISSUE TITLE
AGAINST THE GODS CHAPTERS UNABLE TO OPEN

### ISSUE THREAD

**Issue by jameslikejc** [MakeYourLifeEasier/novel-ebook.com#135]
When I download Chapters 1100-1770 of Against the Gods, and tried to open it, I get a prompt saying: “CANNOT OPEN AGAINST THE GOD: 1100-1777. It is formatted incorrectly or is not a format that Apple Books can open”

**Expected behavior**
I expected the ePub file to open up on the Apple Books 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: IPhone 8 Plus
 - OS: iOS 14.4
 - Browser: Safari
 
![5E81BA12-F12A-47AD-968A-858ECBD8F89E](https://user-images.githubusercontent.com/80329089/110469908-1f353400-80d2-11eb-9c77-2817bf970d6d.jpeg)

**Comment by MichaelGuardian** [comment]
I've just changed the source, could you try again?

**Comment by jameslikejc** [comment]
Ok. Will try now
