### ISSUE TITLE
Download is not working for any Novel

### ISSUE THREAD

**Issue by joydip1203** [MakeYourLifeEasier/novel-ebook.com#139]
**Describe the bug**
Every novel download have been stuck when assimilating the chapters, screenshot attached.
![pic1](https://user-images.githubusercontent.com/80536516/110968094-216eeb00-837d-11eb-9cf4-c868034f821e.jpg)
![pic2](https://user-images.githubusercontent.com/80536516/110968237-4d8a6c00-837d-11eb-98a9-b0a7093607dd.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelGuardian** [comment]
Server is overloaded, nothing I can do there
