### ISSUE TITLE
About novel:ebook(Novel : "My Vampire system") new chapters didn't upload

### ISSUE THREAD

**Issue by krunalj-bit** [MakeYourLifeEasier/novel-ebook.com#140]
**Describe the bug**
New chapters of "My Vampire System" in Novel ebook didn't upload.

**To Reproduce**
1. Go to search bar in Novel ebook webapp
2. Search my vampire system
3. Scroll down to all chapters
4. See error (new chapters after chapter 719 didn't upload)

Usually New chapters upload within one hour after new chapters release, but since tomorrow new chapters released but those chapters didn't upload here, so there might be bug, so please look into this matter

**Screenshots**
![Screenshot_20210317-112159_Chrome](https://user-images.githubusercontent.com/80804610/111423282-0ce07900-8716-11eb-9144-00b42039d27c.jpg)
![Screenshot_20210317-112424_Chrome](https://user-images.githubusercontent.com/80804610/111423293-12d65a00-8716-11eb-926e-d3186487db20.jpg)
![Screenshot_20210317-112445_Chrome](https://user-images.githubusercontent.com/80804610/111423300-1669e100-8716-11eb-9f9f-f7a0e0f0b53a.jpg)
![Screenshot_20210317-112457_Chrome](https://user-images.githubusercontent.com/80804610/111423321-1cf85880-8716-11eb-8a1a-c7aeebd426d2.jpg)

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy M51]
 - OS: [Android 11]
 - Browser [Chrome]
 - Version [89.0.4389.86]

**Comment by MichaelGuardian** [comment]
#44 I have no control over updates on novels.
