### ISSUE TITLE
The divivne Physician's Overbearing Wife

### ISSUE THREAD

**Issue by Night-Sign** [MakeYourLifeEasier/novel-ebook.com#141]
**Describe the bug**

**To Reproduce**
1. Go to '...'Novel ebook
2. Click on '....'search and download
3. Scroll down to '....'chapter 1778
4. See error missing chapter until the end 

**Expected behavior**
 i expect that those missing chapters can be recovered
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelGuardian** [comment]
#44 I don't have control over the chapter content
