### ISSUE TITLE
Prodigiously Amazing Weaponsmith

### ISSUE THREAD

**Issue by Night-Sign** [MakeYourLifeEasier/novel-ebook.com#143]
**Describe the bug**

**To Reproduce**
1. Go to '...' novel ebook search
2. Click on '....' download
3. Scroll down to '....' scroll down until chapter 1393
4. See error Missing chapters starting chapter 1393 until the end

**Expected behavior**
i expect that the missing chapters are recovered
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelGuardian** [comment]
#44
