### ISSUE TITLE
Mesmerizing Ghost Doctor

### ISSUE THREAD

**Issue by Night-Sign** [MakeYourLifeEasier/novel-ebook.com#144]
**Describe the bug**

**To Reproduce**
1. Go to '...' novel ebook and click on search
2. Click on '....' download
3. Scroll down to '....' scroll until the end
some do not have chapter numbers and its chapters are gambled also other chapters are being repost again 
**Expected behavior**
i expect that the gambed chapters are fixed and those with same chapters are removed also the chapters must contain its chapter number to avoid confusion
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelGuardian** [comment]
#44
