### ISSUE TITLE
Supreme Magus chapter overlap

### ISSUE THREAD

**Issue by Magusissupreme** [MakeYourLifeEasier/novel-ebook.com#145]
**Describe the bug**
Chapters 89 and 90 are the same chapter. The issue is similar with some other chapters like 71 and 72 are the same chapter etc. There are more bugs like that so you basically lose chapter 90 and chapter 72. There are more chapters like that but I didn't read past 90 so the best would be to download it fully and see if there are similar issues.

**To Reproduce**
1. Go to chapter 89 and 90 then 71 and 72 after downloading from 1-last chapter or 8-last chapter

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy a20s]
Tested it both with epub on my phone and after converting to mobi on my ebook.

**Comment by Ness67** [comment]
I have experienced the same problem, I want to add that the chapter title is correct but the text is a duplicate from the previous chapter.

**Comment by MichaelGuardian** [comment]
This falls under #44. This is a problem at the data source which I have no control over.
