### ISSUE TITLE
Overgeared double chapter bug

### ISSUE THREAD

**Issue by AR45H** [MakeYourLifeEasier/novel-ebook.com#147]
Hey,

I've only seen this happen on overgeared so far. When I set any chapter range for download the final downloaded epub file contains double chapters for all chapters selected. I've tried with 100 chapters, 50 chapters, and 1 chapter.
https://i.imgur.com/kfkS5kH.png

**Desktop:**
 - OS: Windows 10 20H2
 - Browser Firefox
 - Version 87b2

**Comment by AR45H** [comment]
Same behavior after updating firefox to 87 release. version.

**Comment by AR45H** [comment]
Same behavior with Chrome Version 89.0.4389.90.

**Comment by MichaelGuardian** [comment]
Hey I just checked and it seems that there was an indexing issue with a couple of novels. Reindexed Overgreaded, bug should now be fixed.

**Comment by AR45H** [comment]
> 
> 
> Hey I just checked and it seems that there was an indexing issue with a couple of novels. Reindexed Overgreaded, bug should now be fixed.

Thanks, that fixed it.
