### ISSUE TITLE
Not all chapters of the The Legendary Mechanic exist

### ISSUE THREAD

**Issue by Yash-Kaveeshwar** [MakeYourLifeEasier/novel-ebook.com#15]
The chapters after 479 don't exist on the site despite being available else where. I would suggest changing the source for the site from wuxiaworld.co to some other site which is regularly maintained.

**Comment by MichaelGuardian** [comment]
I might change the source if the issues become more prevalent. Switching the source requires substantial changes to the current codebase, so I'd rather avoid that if possible

**Comment by Yash-Kaveeshwar** [comment]
Fair enough but if you can at some point change the source you should because on wuxiaworld.co because of Qidian privileged chapters many chapters are incomplete. For example Transcending the Nine Heavens, latest chapters are all dummy without any content.

**Comment by MichaelGuardian** [comment]
I'll keep that in mind, just don't expect it to happen anytime soon. Finding a source that has consistent formatting and doesn't complain about the substantial non-monetizable traffic increase is harder said then done.
