### ISSUE TITLE
Cultivation Chat Group

### ISSUE THREAD

**Issue by ianmacdo** [MakeYourLifeEasier/novel-ebook.com#151]
for Cultivation Chat Group

novel-ebook.com is missing chapters that it used to have?

Previously I used this great site to make an epub of chapters 1-1400.  But today when I wanted to check for new chapters the novel-ebook.com only goes from 1-1065.  Missing 300 chapters that used to be here.  and I checked on some other sites and its up to over chapter 1500 now.

**Comment by DiamondBanker** [comment]
UP THIS

**Comment by MichaelGuardian** [comment]
#44 This is a problem with the data source, over which I have no control
