### ISSUE TITLE
Tales of Demons and Gods not donloadable

### ISSUE THREAD

**Issue by myrkjartan** [MakeYourLifeEasier/novel-ebook.com#152]
When i try to download Tales of Demons and Gods, the loading circle (before i get the form whre i cn choose chapters) endlessly spins and nothing else happens. 
I already tried other novels and for those i tried, the download works fine. It seems to be just Tales of Deamons and Gods.

**Comment by NIGHT49** [comment]
i am also having this problem but on several novels

**Comment by MichaelGuardian** [comment]
Fixed
