### ISSUE TITLE
The Human Emperor 

### ISSUE THREAD

**Issue by hybrid13** [MakeYourLifeEasier/novel-ebook.com#153]
The human emperor Novel, chapters are not complete.
50% of chapters are missing.

(((((In preparation, Keguan Please wait a moment, after the updates, you need to refresh the page to get the latest updates!)))) This is Written in the chapters.

**Comment by MichaelGuardian** [comment]
#44 I'll have this on my radar though, if the data source updates the novels I'll reindex and comment on this issue.
