### ISSUE TITLE
Martial Peak Double Chapter's 

### ISSUE THREAD

**Issue by crono969** [MakeYourLifeEasier/novel-ebook.com#156]
Title says it all... Please fix this fast. its really starting to get annoying!

**Comment by crono969** [comment]
Yeah i know i didn't read before posting... Still hopefully someone might see this and do something about it.

**Comment by MichaelGuardian** [comment]
The double chapter bug was fixable. I've edited the do not read ticket and reindexed Martial Peak. Should work fine now.
