### ISSUE TITLE
Empty/corrupted downloads

### ISSUE THREAD

**Issue by blindsoose** [MakeYourLifeEasier/novel-ebook.com#16]
**Describe the bug**
When i try to download random novells, it gives me a download, but when i open the epub it's empty, when i open it in notepad ++ i see some corrupted characters and no actual novel text.
**To Reproduce**
1. Go to 'https://novel-ebook.com'
2. Click on 'pet king'
3.  'Select starting and ending chapters, in my case those were 1 200. Open the downloaded file'

**Expected behavior**
I expected to read, but got corrupted text.

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome]
 - Version [latest]

Additionaly, it happens only with some of the novels, and my range is one million is one of them.

**Comment by MichaelGuardian** [comment]
I just tried Pet King and it works fine on my system. I see some xml parsing errors in chapter 98 but most e-reader can handle this without breaking anything.

Have you tried a different epub reader? Which one are you currently using?
Also .epub files are essentially zip files, so opening it with a text editor like notepad++ won't work.

**Comment by blindsoose** [comment]
Im using balabolka, and actually if i open pet king in notepad++ i can see some propper text, but there's empty lines mostly. Actually, i think i've eeven tried to open it with microsoft edge and it didn't work either. Not sure what's happening, but well, seems i'll have to pass on that novel sadly.

**Comment by blindsoose** [comment]
Ok, just converted that to txt with an online converter and it definately works. Am quite sorry for my stupidity and for the useless issue.
