### ISSUE TITLE
Supreme Magus double chapters AND overwritten chaps

### ISSUE THREAD

**Issue by Shatt3redV01D** [MakeYourLifeEasier/novel-ebook.com#164]
**Describe the bug**
Chapters from 1-55 reoccur
(Chap 1, Chap 1, Chap 2, Chap 2) 
Two part chapters get overwritten by the previous part (Chap 77 "Interludium, Chap 78 "Interludium 2") (The entire "2" chapter gets replaced with the text from "1" rendering "2" missing from the epub)

**To Reproduce**
1. Download the epub from webpage including relevant chapters (I downloaded them all and also tried just downloading the affected chapters it was the same in both cases)
2. Rename the extension to remove .zip
3. Open with any reading application (I use FBReader but I tried 2 more apps to see if it was just the app deff the file)
4. Flip through the first couple of chaps to see them reoccurring, Flip to any double parter "[Title]" "[Title] 2" to see that their contents is the same with "[Title] 2"s chapter just missing.

**Expected behavior**
I wxpected for chapters not to reoccur and for double parters not to be overwritten. (Side note absolutely LOVE your webpage saved me quite a lot of anguish over paying for chapters on Qidian AND the hassle of trying to find epubs for small novels on smaller sites. Youre salvation for any starving binge reader to come across your site)

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A71]
 - OS: [Android]
 - Browser [Google Chrome]
 - Version [Android V11]

**Additional context**
⢀⡴⠑⡄⠀⠀⠀⠀⠀⠀⠀⣀⣀⣤⣤⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠸⡇⠀⠿⡀⠀⠀⠀⣀⡴⢿⣿⣿⣿⣿⣿⣿⣿⣷⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠑⢄⣠⠾⠁⣀⣄⡈⠙⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⢀⡀⠁⠀⠀⠈⠙⠛⠂⠈⣿⣿⣿⣿⣿⠿⡿⢿⣆⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⢀⡾⣁⣀⠀⠴⠂⠙⣗⡀⠀⢻⣿⣿⠭⢤⣴⣦⣤⣹⠀⠀⠀⢀⢴⣶⣆ 
⠀⠀⢀⣾⣿⣿⣿⣷⣮⣽⣾⣿⣥⣴⣿⣿⡿⢂⠔⢚⡿⢿⣿⣦⣴⣾⠁⠸⣼⡿ 
⠀⢀⡞⠁⠙⠻⠿⠟⠉⠀⠛⢹⣿⣿⣿⣿⣿⣌⢤⣼⣿⣾⣿⡟⠉⠀⠀⠀⠀⠀ 
⠀⣾⣷⣶⠇⠀⠀⣤⣄⣀⡀⠈⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀ 
⠀⠉⠈⠉⠀⠀⢦⡈⢻⣿⣿⣿⣶⣶⣶⣶⣤⣽⡹⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⠀⠉⠲⣽⡻⢿⣿⣿⣿⣿⣿⣿⣷⣜⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣷⣶⣮⣭⣽⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⣀⣀⣈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⠀⠹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠛⠻⠿⠿⠿⠿⠛⠉
Thanks again for the good times you're absolute legends/a legend. (Idk how many devs there are heh)

**Comment by MichaelGuardian** [comment]
This issue falls under #44 I double checked as I like to read that one. I'll address that issue with a upcoming beta release hopefully this week.
