### ISSUE TITLE
the mech touch chapters out of order

### ISSUE THREAD

**Issue by AshGospel** [MakeYourLifeEasier/novel-ebook.com#165]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AshGospel** [comment]
The mech touch chapters out of order

**Comment by MichaelGuardian** [comment]
#44 I'll release a beta sometime this month to address the issue
