### ISSUE TITLE
Supreme Magus - Duplicated Content

### ISSUE THREAD

**Issue by kemper451** [MakeYourLifeEasier/novel-ebook.com#168]
The author has many chapters that are like "Title' and the "Title2".  For example, Chapter 77 is Interludium and Chapter 78 is Interludium 2.  In these cases, the entire chapter content is duplicated and the content of the second chapter is then lost.

77 Interludium
After lunch, the group fell asleep

78 Interludium 2
After lunch, the group fell asleep.

**Comment by MichaelGuardian** [comment]
#44, but currently running beta test should fix this issue
