### ISSUE TITLE
Titles not updating with new chapters since 4/22

### ISSUE THREAD

**Issue by moops1** [MakeYourLifeEasier/novel-ebook.com#169]
Since April 22nd all titles I read have had no updates while the actual series is updating(not 100% sure where this pulls from now) which include Monarch of Evernight, Overgeared, supreme magus, chaotic sword god etc

**Comment by MichaelGuardian** [comment]
Thanks for the info. I will release a updated version of the site pretty soon. Just need to do the testing check back in 1-2 days

**Comment by moops1** [comment]
Awesome!  Thank you
