### ISSUE TITLE
Cant access many novel in beta site

### ISSUE THREAD

**Issue by skykissed** [MakeYourLifeEasier/novel-ebook.com#171]
**Describe the bug**
There’s so much novel that cant be accessed using the beta site, and if im using the original site its just not working (the system just said something like packing file blablabla and not downloading).

**Expected behavior**
I hope at least we can access all the novel in the beta sites.

Im using iphone xs max and android too, with many browser such as safari, chrome, and firefox.

**Comment by MichaelGuardian** [comment]
Can you elaborate on "can't be accessed"?

If the last message you see is "packing file", it means it's already finished downloading but failed to create the epub file. What version of android are you using? Have you tried using small chapter ranges? I'll implement a fix for ios during the beta period

**Comment by skykissed** [comment]
Sorry if my wording is complicated, i mean i cant find many title in beta site.

**Comment by MichaelGuardian** [comment]
That is by design. Had to drop quite a few novels for the new version.

**Comment by skykissed** [comment]
Ah i see i see, okay thankyou for the replies ^^
