### ISSUE TITLE
Trash of the count is family

### ISSUE THREAD

**Issue by ArthurKun** [MakeYourLifeEasier/novel-ebook.com#172]
**Describe the bug**
Unable to download the chapters

**To Reproduce**
1. Go to 'novel epubs.com'
2. Click on 'search and type trash of the count is family'
3. Select the amount of chapters to be downloaded and click on download
4. We see the error that it is unable 

 - OS: [ iOS]
 - Browser [safari]
 - Version [latest]

**Comment by MichaelGuardian** [comment]
Check out the beta version, should be working there.
