### ISSUE TITLE
Stuck in the packing file and not downloading

### ISSUE THREAD

**Issue by skykissed** [MakeYourLifeEasier/novel-ebook.com#174]
**Describe the bug**
So i tried to download some novel, and theres some certain novel that cant be downloaded, its stuck in the packing file and not downloading

I’ve been trying using both android and ios, with many browser,  but it still cant be downloaded

**Comment by moops1** [comment]
Which novels and have you tried the beta?

**Comment by skykissed** [comment]
Update

Im using my pc and it can be donwloaded, idk why but in andro and ios with so many browser i still cant download it (trash of the counts family)
