### ISSUE TITLE
unable to download many novels

### ISSUE THREAD

**Issue by joydip1203** [MakeYourLifeEasier/novel-ebook.com#175]
Is the new web page is fully ready?? after check out with beta site I try to download novels but all it showing packing which taking almost huge time & also not completed either, when it will be fixed???

**Comment by MichaelGuardian** [comment]
Hm, I've tried replicating that issue on my devices but it never popped up. I just added some error tracking so I can pinpoint the issue and update it in the future. Sometimes there might be issues with timeouts, so try downloading just a few chapters at once if your on a mobile phone or use a desktop browser.

**Comment by MichaelGuardian** [comment]
Are you using Android 4.4?
