### ISSUE TITLE
Ending Chapter Download Not Inclusive

### ISSUE THREAD

**Issue by NightB1ade** [MakeYourLifeEasier/novel-ebook.com#178]
**Describe the bug**
getChapters downloading does not include the ending chapter.

Subsequently one is not able to download the last chapter of any novel.

**To Reproduce**
1. Choose any novel
2. Choose any starting chapter
3. Choose any ending chapter
4. Download
5. Downloaded epub does not include ending chapter

**Expected behavior**
Selected ending chapter is inclusive of the download, also the ability therefore to download the last chapter

**Screenshots**
![Capture](https://user-images.githubusercontent.com/18259801/118806050-8889ae00-b89e-11eb-80db-2935e193e70e.PNG)

To rectify, I believe this should be `i <= r` (or other methods exist, this just being one suggestion)

**Additional Information**
Had a search on issues in regards to last chapter, final chapter, ending chapter etc.  Didn't spot anything in particular that was relevant, but would happily be corrected if there are.

**Comment by NightB1ade** [comment]
Come to think of it, this'll also end up with a blank epub if a single chapter is attempted to be downloaded

**Comment by MichaelGuardian** [comment]
Thanks for reporting this issue!

Yea something went wrong with yesterdays deploy and the code got overwritten by an old test version. 
`i <= r` is how it supposed to be. It should be fixed now.

**Comment by NightB1ade** [comment]
Confirmed it works ;)  Ta muchly!
