### ISSUE TITLE
Chapters with the same Name are the same

### ISSUE THREAD

**Issue by SamyFawzy** [MakeYourLifeEasier/novel-ebook.com#182]
In the Book Supreme Magus and the Trash Count Chapters with same Name are always the same. It might be happening in other books too.
For example:
Ice Cream 1
Ice Cream 2

And Ice Cream 2 is just like Ice Cream 1

**Comment by MichaelGuardian** [comment]
What device are you using?

**Comment by SamyFawzy** [comment]
I am using an iMac

**Comment by MichaelGuardian** [comment]
Hm, I couldn't replicate this particular issue. Could you upload the file you downloaded? I'll take a look.

**Comment by SamyFawzy** [comment]
I tried downloading something to show you an example, but now it doesn't even download. It always gets stuck.

**Comment by SamyFawzy** [comment]
![Screen Shot 2021-05-25 at ](https://user-images.githubusercontent.com/52803006/119491688-80c67f80-bd5e-11eb-9680-bd0b5cd59e29.png)
![Screen Shot 2021-05-25 ](https://user-images.githubusercontent.com/52803006/119491870-bc614980-bd5e-11eb-9a02-adcfec299319.png)

**Comment by MichaelGuardian** [comment]
I think I found the issue for both problems. Could you give it another shot?

**Comment by SamyFawzy** [comment]
It's working now and there are no repeating chapters. Thanks
