### ISSUE TITLE
Novels Missing

### ISSUE THREAD

**Issue by joydip1203** [MakeYourLifeEasier/novel-ebook.com#183]
Some novels are missing after the updated website is lived(e.g. :-Legend of the great sage, Sage Monarch, THE KING OF THE UNIVERSE).Also the getting chapter contents is horribly slow which is way faster earlier, is it will be fixed ??

**Comment by MichaelGuardian** [comment]
Novels got removed on purpose, and won't be readded for the foreseeable future.

Speed is slow right now and will hopefully pick up a bit in the next couple of weeks.
