### ISSUE TITLE
Gourmet of another world error chapters

### ISSUE THREAD

**Issue by meowth240** [MakeYourLifeEasier/novel-ebook.com#186]
some chapters (from 1 to 1466) keep showing the same notice: "The above error occurred while the Web server was processing your request. Please contact us if you think this is a server error. Thank you.". The titles show up normally and chapters after them still good so please check the source. Thank you in advance!!!
Edit: I just find out that some chapters after 1466 have the same notice too so please check them all, Thanks a lot!
Edit2: "I Have a Mansion in the Post-apocalyptic World" got the same error

**Comment by MichaelGuardian** [comment]
Novels with errors: 
- Gourmet of another world
- I Have a Mansion in the Post-apocalyptic World

Thanks for reporting the issue! I found the problem the fix will be released with the next backend update.

**Comment by meowth240** [comment]
Thank you, and by the way some of the chapters of "My Father in Law is Lu Bu" is missing and chapter 294 got replace by 291 so please check them too.

**Comment by MichaelGuardian** [comment]
The issues should be fixed. If there are still problems, feel free to open up a new ticket.
