### ISSUE TITLE
Recent chapters missing

### ISSUE THREAD

**Issue by moops1** [MakeYourLifeEasier/novel-ebook.com#187]
When downloading several novels such as supreme magus, the first order, or abe the wizard chapters posted in the last - 2 weeks are coming up as chapter missing once opening the epub file.  They are also taking an abnormally long time to download when the said novel has chapters missing.  I want to say this started in the past week and has occurred for most novels I read.  I a! On Android 7.

**Comment by MichaelGuardian** [comment]
#44
