### ISSUE TITLE
Martial Peak chapter error

### ISSUE THREAD

**Issue by agente-x** [MakeYourLifeEasier/novel-ebook.com#189]
the novel contains missing chapters filled in with chapters from other novels from what should be chapter 2023 and from 2026 to 2028.

**Desktop (please complete the following information):**
 - OS: windows 7 ultimate sp1 x86
 - Browser chrome
 - Version Versión 91.0.4472.101 (Build oficial) (32 bits)

**Comment by MichaelGuardian** [comment]
Should be fixed
