### ISSUE TITLE
Doesn't get 't' in the end of chapter name

### ISSUE THREAD

**Issue by GabrielGuzman05** [MakeYourLifeEasier/novel-ebook.com#19]
**Describe the bug**
When geting chapter 254-331 from Dragon Prince Yuan the chapter name loses a 't' at the end of the chapter name. For example in "Chapter 322 Bait" it becomes "Chapter 322 Bai" or in "Chapter 323 Get" it becomes "Chapter 323 Ge"

**Comment by Okedele** [comment]
Same for every novel. Chapter titles ending with 't' loses the 't'

**Comment by MichaelGuardian** [comment]
Fixed
