### ISSUE TITLE
Trash of the count family latest chapter

### ISSUE THREAD

**Issue by nivianda** [MakeYourLifeEasier/novel-ebook.com#192]
I tried to download from chapter 675-681 the latest in the web but i got blank document. Turned out when I download from ch 600-681, chapter after 677 said chapter is missing. The host of the novel is EAP based on the 677, and they had other chapter untill 682 already out. Is it the host page issue then?

**Comment by nivianda** [comment]
Or...if the host/source is not EAP, please update if can. Thank you so much for the site btw!!

**Comment by MichaelGuardian** [comment]
I believe it's an issue with how the caching is handled. I'll clear once I find the time to work on the backend

**Comment by MichaelGuardian** [comment]
Fixed
