### ISSUE TITLE
Forty Millenniums of Cultivation Chapter server error

### ISSUE THREAD

**Issue by ashbk37** [MakeYourLifeEasier/novel-ebook.com#195]
Chapters from 2666 to 2711 are already released on other sites, but shown error after downloaded from the site. 
![Screenshot_20210624-181158481](https://user-images.githubusercontent.com/53833903/123264620-d46fe880-d517-11eb-8afd-a3432dbecea9.jpg)

**Comment by MichaelGuardian** [comment]
This issue seems to be related to other novels. I've mentioned this novel in issue #215 so I have a better overview. Currently working on a fix.
