### ISSUE TITLE
MMORPG Rebirth of the Legendary Guardian

### ISSUE THREAD

**Issue by Snowflake101** [MakeYourLifeEasier/novel-ebook.com#198]
Corrupted source. Upon trying to download content instead of expected results the content of every xhtml document is largely the same. i.e. 

This error occurs when trying to download Chapters 1-100 ( from https://novel-ebook.com ). 

Attached is the first chapter.
[0.txt](https://github.com/MakeYourLifeEasier/novel-ebook.com/files/6757220/0.txt)

**Comment by MichaelGuardian** [comment]
This issue seems to be related to other novels. I've mentioned this novel in issue #215 so I have a better overview. Currently working on a fix.
