### ISSUE TITLE
Commanding Wind and Cloud error 

### ISSUE THREAD

**Issue by Askall09** [MakeYourLifeEasier/novel-ebook.com#199]
**Describe the bug**
Server error for the chapters the same as the other reported novel bugs. Thank you
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by unholydeathbat** [comment]
Not able to download the full novel, most of the chapters are missing or there is an error as the downloaded file size is around 646kb as it is not possible for having a novel having 650 chapters

**Comment by MichaelGuardian** [comment]
This issue seems to be related to other novels. I've mentioned this novel in issue #215 so I have a better overview. Currently working on a fix.
