### ISSUE TITLE
Not downloading full chapters

### ISSUE THREAD

**Issue by ARX-7** [MakeYourLifeEasier/novel-ebook.com#2]
Trying to download all of nine star hegemon body art.

Chapter 8 is just empty and chapter 11 has only the first half, not sure how far this has happened elsewhere, but it's what I noticed.

Edit: also on chapter 12, I may have missed it in the earlier chapters as I think there is some stuff missing

From web app

**Comment by MichaelGuardian** [comment]
Thanks for posting!

I'll take a look into it once I'm home. If I recall correctly I was just about to rewrite the parser anyway.

**Comment by MichaelGuardian** [comment]
Sry for the delay but I reworte the majority of the codebase and didn't want to invest to much time in the old one.

The issue is fixed.
