### ISSUE TITLE
Missing Chapters & Request

### ISSUE THREAD

**Issue by Lifeslaver** [MakeYourLifeEasier/novel-ebook.com#201]
Missing Chapters on:
Summoning the Holy Sword 1354-END
MMORPG_ Martial Gamer 1427-next
Martial Peak 2021-next
History's Strongest Senior Brother 1469-next
Extraordinary Genius 1481-next
Cultivation Chat Group 1581- next

Emperor’s Domination ch3636- replaced by side stories and some later chapters missing

Using Google Chrome

**Comment by wiseman212** [comment]
yep same

**Comment by MichaelGuardian** [comment]
I've fixed the majority of those. 
History's Strongest Senior Brother still has some broken chapters and I'll take a closer look at a later date.
Extraordinary Genius is not available up to this chapter, limited by the data source this site uses.
Emperor’s Domination problems also seem to stem from the data source but the missing chapters should be fixed.

I'll close this issue for now and mention the broken novels in issue #215 , so I have a better overview of the broken novels.
