### ISSUE TITLE
Ebook download in Rar format

### ISSUE THREAD

**Issue by Natands** [MakeYourLifeEasier/novel-ebook.com#203]
**Describe the bug**
Once the files is compilated the ebook is download in rar format and it's not readable.

**To Reproduce**
1. Go to Unrivalied Medicine God with the firefox in desktop
2. Click on 165 chapther to 2276 chapther and compile.
3. Download file and will be in rar format

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser [firefox]
 - Version [90.0 (64-bits)]

**Additional context**
It's happend with other novels too.

**Comment by MichaelGuardian** [comment]
This is a problem with your system. I'm not sure what causes this issue for you but .rar files where never supported and I'm certain that this file extension was never used in this application.
