### ISSUE TITLE
"nine star hegemon body art" is not downloading properly. showing chapter missing.

### ISSUE THREAD

**Issue by akash333777** [MakeYourLifeEasier/novel-ebook.com#205]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wiseman212** [comment]
same same

**Comment by MichaelGuardian** [comment]
Should be fixed
