### ISSUE TITLE
Chapters are being confused

### ISSUE THREAD

**Issue by AdaptiveAlchemist** [MakeYourLifeEasier/novel-ebook.com#21]
I tried downloading "City of Sin". It downloaded chapter 27 from Book 3 instead of Book 2. I selected all chapters. 

Just download all chapters and you will see chapter 27 for book 2 has been replaced with chapter 27 from Book 3. Book 3 has its own chapter 27 correctly. 

I tried it on desktop with Mozilla Firefox and on Android via chrome. Same result.

**Comment by MichaelGuardian** [comment]
Sadly this bug is a result of the used source material not the webapp itself, so I cant offer a bugfix. However I will keep this in mind and fix it when I have the time to launch v3 of this application

**Comment by AdaptiveAlchemist** [comment]
Thank you.
