### ISSUE TITLE
Once Upon a Time, There Was a Spirit Sword Mountain

### ISSUE THREAD

**Issue by kemper451** [MakeYourLifeEasier/novel-ebook.com#212]
Downloaded 820 - 850.  Each chapter reads:

The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.

**Comment by MichaelGuardian** [comment]
This issue seems to be related to other novels. I've mentioned this novel in issue #215 so I have a better overview. Currently working on a fix.
