### ISSUE TITLE
download issues

### ISSUE THREAD

**Issue by DunnSmith** [MakeYourLifeEasier/novel-ebook.com#214]
Thank you "novel-ebook" for making this easy to use simple but effective website THANK YOU.
But there is this problem that need to be fixed asap PLEASE.
It happens when i want to download all the chpters of "Supreme Magus" or  "Life, Once Again" it's slow and painful
but the problem  is after the download the 100 or so last chapters are missing. 
so PLEASE fix this ASAP i love you THANKS.

**Comment by MichaelGuardian** [comment]
Fixed
