### ISSUE TITLE
Emperor’s Domination_ 3636-3645 replaced chapters

### ISSUE THREAD

**Issue by Lifeslaver** [MakeYourLifeEasier/novel-ebook.com#216]
Emperor’s Domination_ 3636-3645 replaced by side stories
Hope you'll correct them
Thx

**Comment by Lifeslaver** [comment]
The Legend of Chu Qiao_ Division 11's Princess Agent
Some missing Chapters and Chapters randomized, not in order

Request:
Beauty accompanying manual
Spirit cultivation
Journey To Become A True God

**Comment by MichaelGuardian** [comment]
I'll take a look at Emperor's Domination shortly. The missing chapters and the wrong order should be fixed automatically after some time, so just try again.

It's not possible the request novels at the moment

**Comment by MichaelGuardian** [comment]
Emperor's Domination chapters are fixed
