### ISSUE TITLE
Error on Stone Age Husband Raising Journal

### ISSUE THREAD

**Issue by Himitsuni** [MakeYourLifeEasier/novel-ebook.com#217]
There is an error in the "Stone Age Husband Raising Journal" novel.

Multiple unknown chapters, e.g. Chapter 3 is being replaced by Chapter 819 from an unknown novel.
Multiple duplicated chapters, e.g. Chapter 10 is being duplicated.

I'm not sure whether this is a bug or the file itself contains these errors.
I had downloaded several other novels with duplicated/missing chapters before, but after waiting for few days and redownloading them, the files came out fine. I have tried this one for a month now but it came out the same every time.
Please check if this is fixable. Thank you in advance.

**Comment by MichaelGuardian** [comment]
Stone Age Husband Raising Journal should be fixed now
