### ISSUE TITLE
Cultivation Chat Group Chapter 1300-1400 bug

### ISSUE THREAD

**Issue by crono969** [MakeYourLifeEasier/novel-ebook.com#218]
I downloaded all the chapters from 1000 to 1649 and it didnt work so i tried smaller packages of 100 chapters and it worked for all except 1300 to 1400 i tried often enough to report it as a bug.

btw i use balabolka to read the epub. I checked the files with notepad the text seems to be there it just wont show up on balabolka.

"Balabolka is a text to speech software"

**Comment by crono969** [comment]
So i tried to help solve the problem by trying to find out EXACTLY where the problem was and i think i got it!
I isolated the problem to the first 6 chapters 1307 to 1400 worked just fine! so take a look at chapter 1300 to 1306.
If any of these 6 chapters are in the package the whole package wont load.

Hope that helps ☺

**Comment by MichaelGuardian** [comment]
This is a problem with chapter 1305 and it's the same issue as #67 . I'll fix it next time I push a front-end update.
