### ISSUE TITLE
Chapter content is missing

### ISSUE THREAD

**Issue by smlunt** [MakeYourLifeEasier/novel-ebook.com#22]
I downloaded Unrivaled Tang Sect, it was good up until Chapter 18.1-19.4 where the content is replaced with:
"In preparation, Keguan Please wait a moment, after the updates, you need to refresh the page to get the latest updates!"

Searching through the epub I see a few other chapters have the same issue (72, 79, 324)

**Comment by MichaelGuardian** [comment]
This is not a problem with the application, but with the source material. Sadly I can not offer a fix as of now. Might add multiple sources in the future.
