### ISSUE TITLE
Requesting Transdimensional Marketing

### ISSUE THREAD

**Issue by DiamondBanker** [MakeYourLifeEasier/novel-ebook.com#220]
Hi, I cannot find Transdimensinal Marketing.

Can you please add it for me? Here's the link

https://boxnovel.com/novel/transdimensional-marketing/

**Comment by MichaelGuardian** [comment]
#44 Currently not gonna add new novels

**Comment by DiamondBanker** [comment]
Why :(

Sent from Yahoo Mail on Android 
 
  On Fri, Aug 27, 2021 at 13:41, Michael ***@***.***> wrote:   


#44 Currently not gonna add new novels

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MichaelGuardian** [comment]
Time constrains

**Comment by DiamondBanker** [comment]
:(((

Sent from Yahoo Mail on Android 
 
  On Fri, Aug 27, 2021 at 14:13, Michael ***@***.***> wrote:   


Time constrains

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
