### ISSUE TITLE
Missing chapters

### ISSUE THREAD

**Issue by wiseman212** [MakeYourLifeEasier/novel-ebook.com#221]
Missing chapters in these Contemporary Romance novels:

Mr. CEO, Spoil me 100 Percent!
Trial Marriage Husband_ Need to Work Hard
Reincarnation Of The Businesswoman At School
Perfect Secret Love: The Bad New Wife is a Little Sweet
A Star Reborn_ The Queen’s Return
reborn at boot camp: general, dont mess around

**Comment by Seank98** [comment]
Chapter 124 of Tondemo Skill de Isekai Hourou Meshi has been replaced by 370 of some other book

**Comment by Seank98** [comment]
Chapters: 59, 153, 196, 213, 227, 245, and 255 of The Death Mage Who Doesn't Want a Fourth Time are replaced by other chapters

**Comment by TianxaWushuang** [comment]
HI. Chapter 272.1 of Battle Frenzy replaced by the chapter 907 of another novel

**Comment by Seank98** [comment]
Why isn't Botsuraku Yotei Nanode, Kajishokunin wo Mezasu being updated?

**Comment by Seank98** [comment]
Shikkaku Mon no Saikyou Kenja_ Sekai Saikyou no Kenja ga Sarani Tsuyoku Naru Tameni Tenseishimashita is no longer available for updates because the author has removed all past chapters and stated he will no longer be working with that website any longer.

**Comment by Seank98** [comment]
The World of Otome Games is Tough For Mobs is currently on volume 7.
Volume 6 can be found at jnovels.com.

**Comment by MichaelGuardian** [comment]
Thanks for the reports. I'll update them during the next maintenance period at some point within the next 10 days

**Comment by meowth240** [comment]
Some chapters in Bring the farm to live in another world are replaced by other chapters too

**Comment by Seank98** [comment]
Demon Hunter and Tales of Demons and Gods have a repeat.

**Comment by MichaelGuardian** [comment]
Alright I believe I finally found the issue that has caused these problems. Thanks for reporting these since it helped me out a ton figuring out what was wrong!
If any more problems arise, feel free to open up a new issue. Also please add the specific chapter if applicable so I don't have to go through the whole novel every time (my backlog is big enough).

If you find issues posted in this thread still not fixed, please open up a new issue :)
