### ISSUE TITLE
there are many novels which went missing, that I had downloaded in the past.

### ISSUE THREAD

**Issue by aki277** [MakeYourLifeEasier/novel-ebook.com#222]
**Describe the bug**
missing many novels previously available

**To Reproduce**
1. Go to novel-ebook.com
2. Click on the search 
3. Type "New age of Summoners" in the search tab. (I am taking an example) 
4. No novel found of the name

**Expected behavior**
I downloaded the file of the above one and many others like "Reincarnation of a living god" etc on this site but I am unable to find them now

**Additional context**
I will add those files for reference
[New Age Of Summoners_ 1-577.epub.zip](https://github.com/MakeYourLifeEasier/novel-ebook.com/files/7059854/New.Age.Of.Summoners_.1-577.epub.zip)
[Reincarnation of a living god_ 1-282.epub.zip](https://github.com/MakeYourLifeEasier/novel-ebook.com/files/7059858/Reincarnation.of.a.living.god_.1-282.epub.zip)

**Comment by MichaelGuardian** [comment]
#44 Some where removed for various reasons, will not be added in the near future.

**Comment by aki277** [comment]
ok, thanks for the response.
