### ISSUE TITLE
Please add ScribbleHub to supported websites

### ISSUE THREAD

**Issue by Emasoft** [MakeYourLifeEasier/novel-ebook.com#223]
Please add ScribbleHub to supported websites.
For example https://www.scribblehub.com/series/186389/the-way-of-the-dao/

**Comment by MichaelGuardian** [comment]
Sadly I don't really have time to add new sources. There are some changes that need to be made to the front-end to accommodate new sources and the way the backend works also doesn't allow for me to just write a parser and drop a list of links.

I'll close this issue for now and if at some point I find the time to add new sources I'll have ScribbleHub in mind.
