### ISSUE TITLE
eBook format 

### ISSUE THREAD

**Issue by JadeEmpress** [MakeYourLifeEasier/novel-ebook.com#224]
Hello. I'm eternally grateful for your genius in supplying us with amazing ebooks, but I'm at a loss as regards the current format. The books used to be uploaded in epub format but now it's a zip folder with XHTML files. It's difficult to read and I would like to plead that you resume the epub format or advise the easiest way I can convert the XHTML chapters to a single epub file. Thank you.

**Comment by moops1** [comment]
You can go in file manager and delete the .zip from end of file a pain in the butt but does fix it

**Comment by MichaelGuardian** [comment]
Yep, this is not a change in the code but an issue with some mobile devices. Just change the file extension or try a different web browser. All files are still valid .epub files.

**Comment by JadeEmpress** [comment]
Thank you so much for the advice. It worked! 💃💃💃
