### ISSUE TITLE
Nine Star Hegemon Body Arts: all chapters from 1734 to 2279 missing

### ISSUE THREAD

**Issue by Emasoft** [MakeYourLifeEasier/novel-ebook.com#228]
Epub for Nine Star Hegemon Body Arts has bugs. All chapters from 1734 to 2279 are missing! 

The header of the empty chapters reads:
"Chapter Missing
Some chapters that should be here are missing.
We're sorry for the inconvenience :("

It is not related to the source website. I checked WW and the chapters are all online.

**Comment by MichaelGuardian** [comment]
Should be fixed. If you encounter this error in the future, try downloading the novel again, looks like a caching issue.
