### ISSUE TITLE
I Can't Find These Novels, Can You Please Add Them

### ISSUE THREAD

**Issue by Sholarrr** [MakeYourLifeEasier/novel-ebook.com#229]
Hello developer,

I'm making a request for you to please help me add the following novels:
https://www.wuxiaworld.com/novel/necropolis-immortal
https://www.wuxiaworld.com/novel/keyboard-immortal
https://www.wuxiaworld.com/novel/star-odyssey

Thanks in advance.

**Comment by Ryu643** [comment]
synchronizing the novels with Novel Updates so you have all the novels and chapters that transducers could do that
there are many missing romances
mainly shoujo and bls

**Comment by Emasoft** [comment]
Please merge this with the main thread about missing novels

https://github.com/MakeYourLifeEasier/novel-ebook.com/issues/149

**Comment by MichaelGuardian** [comment]
Closed since this is a duplicate. Please refer to issue #149
