### ISSUE TITLE
Linebreak tags are removed, breaking formatting

### ISSUE THREAD

**Issue by q00u** [MakeYourLifeEasier/novel-ebook.com#23]
**Describe the bug**
Paragraph tags are kept. `<p>`
Linebreak tags are not. `<br>`

**To Reproduce**
1. Look at any novel that has `<br>` tags.

**Expected behavior**
Formatting should be preserved.

**Comment by MichaelGuardian** [comment]
Could you add an example for a novel with broken formatting due to missing br tags?

Currently the br tags are deliberately removed as it would generally result in 2 line breaks per sentence in most novels.

**Comment by q00u** [comment]
The Novel's Extra (on novel-ebook as "The Novel Is Extra" but that's a separate issue)

First lines (raw) are:

`<p>===<br>[Kim Suho]<br>17 – 27 years old in the story<br>A righteous, honest man and a hard-worker.`

Which _should_ render as:

> ===
> [Kim Suho]
> 17 – 27 years old in the story
> A righteous, honest man and a hard-worker.

Rendered by novel-ebook as:

![2020-01-12 09_44_45-The Novel is Extra_ 0-379  EPUB  - E-book viewer](https://user-images.githubusercontent.com/892302/72223094-5a64c300-3520-11ea-8931-ebbd95b18444.png)

**Comment by MichaelGuardian** [comment]
I've checked through some novels and the formatting is inconsistant so I won't remove the line of code for now. I'll add a small checkbox on the site for different formatting styles in the future.

**Comment by MichaelGuardian** [comment]
As always, fixed in a timely manner!
