### ISSUE TITLE
Lost or missing novel

### ISSUE THREAD

**Issue by Seank98** [MakeYourLifeEasier/novel-ebook.com#230]
**Describe the bug**

**The novel Itai no wa Iya nanode Bōgyo-Ryoku ni Kyokufuri Shitai to Omoimasu seems to be missing.**

**To Reproduce**

**Was there before most recent update and not there now.**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelGuardian** [comment]
Sadly I can't bring this back since it's been removed by the data source this site uses.
