### ISSUE TITLE
No chapter showing

### ISSUE THREAD

**Issue by Peguinblip** [MakeYourLifeEasier/novel-ebook.com#232]
**Describe the bug**
There is no chapters to select and it onlg shows "www.cloidfare.com" as the chapter. 

**To Reproduce**
1. Go to any novel
2. Click on chapter start or chapter end
3: chapter only shows "www.cloudfare.com"

**Expected behavior**
Select chapters to download

**Smartphone (please complete the following information):**
 - Device: P7 2019
 - OS: android]
 - Chrome

 - Version: latest

**Additional context**
None

**Comment by MichaelGuardian** [comment]
Thanks for reporting the issue, working on it right now.

**Comment by MichaelGuardian** [comment]
Fixed
