### ISSUE TITLE
About the new Datasource poll

### ISSUE THREAD

**Issue by Emasoft** [MakeYourLifeEasier/novel-ebook.com#233]
You asked our opinions on the current Datasource for novels. 
The current Datasource is very good. Changing it would likely cause the loss of some important/rare novels. But this Datasource is still missing some popular novels from important websites. Just look at the missing novels thread here https://github.com/MakeYourLifeEasier/novel-ebook.com/issues/149 
The best solution would be to support multiple Datasources. But this option was not on the poll, so I suggest it here.

**Comment by MichaelGuardian** [comment]
It's just more work I fear. Right now I'm just happy when everything runs again. But thanks for the suggestion!

**Comment by odysse2000** [comment]
Hello i would to know if the french version of the website novelebook is your work  ?
