### ISSUE TITLE
Can you get more chapters for this novel

### ISSUE THREAD

**Issue by chaitanya44444** [MakeYourLifeEasier/novel-ebook.com#234]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
there are 3k chapters on other website but I read on kindle so I download from the website and  I noticed apotheosis ascension to godhood  only has 60 chapters  for download 

**Describe alternatives you've considered**

**Additional context**

**Comment by MichaelGuardian** [comment]
#44
