### ISSUE TITLE
Another Infinite loading

### ISSUE THREAD

**Issue by teller2006** [MakeYourLifeEasier/novel-ebook.com#26]
**Describe the bug**
When click to the "A Record of a Mortal's Journey to Immortality" it just keep loading and never show anythng else.

**Screenshots**
![image](https://user-images.githubusercontent.com/60510186/73540507-8065ef00-445e-11ea-987e-b59bbe4942e6.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - Version 72.0.2 (64-bit)

**Comment by MichaelGuardian** [comment]
#13 
It's the same issue. The reason for the infite loading is because of an encoding error in urls containing non-ascii characters.

For this novel just search for "A Record of a Mortal is Journey to Immortality", that one works
