### ISSUE TITLE
Chapter title number is misleading. 

### ISSUE THREAD

**Issue by fugogugo** [MakeYourLifeEasier/novel-ebook.com#29]
I just found out this amazing web-app and I feel very grateful for it.  I just have some little thing that might be able to improve it

**Describe the bug**
So I tried to download Chapter 1 - 100 of Trash of Count Family
![image](https://user-images.githubusercontent.com/1118608/79688226-126bdf80-8277-11ea-9ed4-66a9341172aa.png)

Yet the resulting epub title is Chapter 0-99
![image](https://user-images.githubusercontent.com/1118608/79688255-52cb5d80-8277-11ea-9c1d-4348611f443b.png)

as a programmer I understand that index start at 0 so this can quite make sense. but for regular user this could be misleading

**Comment by MichaelGuardian** [comment]
Chapter index now starts at 1
