### ISSUE TITLE
Books not displayed

### ISSUE THREAD

**Issue by EternalTrail** [MakeYourLifeEasier/novel-ebook.com#3]
**Describe the bug**
All books are displayed when page is loaded initially. When you type something into the search bar and delete it, no books appear.

**To Reproduce**
1. Type anything into the search bar
2. Delete what you typed
3. No books displayed

**Expected behavior**
When nothing is typed in, all books should be displayed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Brave Browser
 - Version : 0.64.77 (based on Chromium: 74.0.3729.169)

**Comment by MichaelGuardian** [comment]
Thanks for the report. The issue has been fixed.
