### ISSUE TITLE
Not downloading 

### ISSUE THREAD

**Issue by Gobdu** [MakeYourLifeEasier/novel-ebook.com#34]
Whenever I download a chapter, once it reaches 100 percent it says "almost finished.epub is getting packed" and then it proceeds to stay like that and never actually download. Here is a picture of what it stays at after reaching 100 percent.
![Screenshot_20200606-022402_Samsung Internet](https://user-images.githubusercontent.com/66508566/83937683-fe375f80-a79c-11ea-9b8c-72d9fae58828.jpg)

**Comment by MichaelGuardian** [comment]
This means that the content is already downloaded, but that there was a problem creating the .epub file.

What OS Version are you running and which browser did you use? It might work with a different browser.

**Comment by Gobdu** [comment]
Ya I was using samsung internet and it showed this. If I used google chrome it would make a zip file and once extracted every chapter would have to be opened separately. I ended up using firefox as you said try different browsers and firefox worked for me so I'll just use that from now on. Thanks for the help : )
