### ISSUE TITLE
Recording the wrong chapter when a chapter has numeral after it.

### ISSUE THREAD

**Issue by tbesmer** [MakeYourLifeEasier/novel-ebook.com#35]
Recording the wrong chapter when a chapter has numeral after it. This is happening with the supreme magus at the very least. 
![3413413413413](https://user-images.githubusercontent.com/31417658/84192948-b9474d80-aa68-11ea-9d99-c0190f986840.PNG)

If you download the following you should see that 73 Day Two and 74 Day Two 2 are resulting the same chapter. This is incorrect.

**Comment by tbesmer** [comment]
[Supreme Magus_ 82-85.pdf](https://github.com/MakeYourLifeEasier/novel-ebook.com/files/4754523/Supreme.Magus_.82-85.pdf)

Another example with the chapters 77 Interludium and 78 Interludium 2

**Comment by Majeed2096** [comment]
I have noticed this issue in supreme magus with all the chapter with the same name but different number between the bracket

**Comment by moops1** [comment]
Same problem any alternatives for this novel?

**Comment by peppyadventurer** [comment]
Incorrect chapter order in Inevitable Road To Divinity
![image](https://user-images.githubusercontent.com/70425151/91629863-37711b80-e9ea-11ea-9cc7-e196fb8d0f85.png)

**Comment by MichaelGuardian** [comment]
Sadly I can't fix chapter order with the current backend. New backend should fix this problem, beta will launch somewhere next week

**Comment by MichaelGuardian** [comment]
Can't fix this as its a problem with the aggregator.
