### ISSUE TITLE
Some part of a chapter is missing : Lord of the Mysteries ch 609

### ISSUE THREAD

**Issue by Ness67** [MakeYourLifeEasier/novel-ebook.com#36]
It seem that a part of the chapter 609 of Lord of the Mysteries is missing from the epub generated by the web app. It can easily be check by comparing the version on webnovel.com and the generated one.
Good debugging ;)

**Comment by MichaelGuardian** [comment]
I don't store the chapter content, nor do I crawl webnovel.com. I'll try to add different sources of the content in order to avoid incomplete chapters in the future.
Thanks for your report
