### ISSUE TITLE
Just make the CoverPage a white image with the only the title

### ISSUE THREAD

**Issue by ianmacdo** [MakeYourLifeEasier/novel-ebook.com#38]
Thanks for this awesome resource, my only complaint is how it creates a default coverpage image of the first page of the novel.  Right now it looks sortof messy on Ebooks,  when the device is sleeping its always just showing the first page of text.

A much better solution would be to create a coverpage/image that is just the title of the novel and maybe the chapters that are included.

Would look much more professional, and clean

Thanks

**Comment by MichaelGuardian** [comment]
There is actually a feature to use the real covers that are available for the novels. Some update broke this feature, but I'll fix it eventually
