### ISSUE TITLE
Database dosn't update Martial God Asura - no new chapters on the list

### ISSUE THREAD

**Issue by xenon205** [MakeYourLifeEasier/novel-ebook.com#4]
Database dosn't update Martial God Asura - no new chapters on the list. I don't know if other titles are working ok or only this one is down

**Comment by MichaelGuardian** [comment]
Sadly, I do not have control over datebase containing the available chapters. The novels are, as far as I am aware, not updated in real time.

The only thing I can tell for certain is that the site caches requests for each novel for 1 hour, independent of new chapters added or not. So if you expect a chapter update wait 1 hour and try again.
Hope this information helps.
