### ISSUE TITLE
No updated chapters of I reincarnated as a stick

### ISSUE THREAD

**Issue by aki-77** [MakeYourLifeEasier/novel-ebook.com#43]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelGuardian** [comment]
I have no control over the update speeds, but I keep an eye on possible solutions

**Comment by aki-77** [comment]
Now there are no chapters available at all
