### ISSUE TITLE
Stuck in novel loading screen

### ISSUE THREAD

**Issue by mHaisham** [MakeYourLifeEasier/novel-ebook.com#45]
**Describe the bug**
website is stuck in loading screen

**To Reproduce**
Click on any novel title

**Expected behavior**
Load to download screen

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 63

**Comment by MichaelGuardian** [comment]
Currently undergoing maintenance. Site should be back up in 2-3 hours

**Comment by mHaisham** [comment]
Oh. Ok

**Comment by MichaelGuardian** [comment]
Site is online again

**Comment by mHaisham** [comment]
### it still doesnt load

![image](https://user-images.githubusercontent.com/47662901/89914290-3b412780-dc0e-11ea-879e-98d5314bc2b8.png)

**Comment by MichaelGuardian** [comment]
Fixed
