### ISSUE TITLE
Overgeared wrong starting chapter

### ISSUE THREAD

**Issue by ZetiX** [MakeYourLifeEasier/novel-ebook.com#46]
**Describe the bug**
For the novel Overgeared, the chapters list starts with 1001 rather than 1. However, after downloading the chapters when selecting chapter 1 - end, it'll generate a epub with chapters starting from 1 - end but skip 1000-1100.

Downloading chapters 1001 - end chapter creates a epub with 1001 as the starting chapter instead of chapter 1.

**To Reproduce**
1. Go to Site and search for overgeared and select it
2. Click on Starting chapter
3. See error with wrong starting chapter

**Expected behavior**
Starting chapter should be 1 and chapters 1001-1100 should start after 1000

**Screenshots**
![image](https://user-images.githubusercontent.com/11995201/90282035-b0457480-de3b-11ea-91d2-503b8a3b4afe.png)

**Desktop (please complete the following information):**
 - Browser: Firefox 79.0
 - OS: Windows 10 64-bit

**Comment by MichaelGuardian** [comment]
This is a problem with the content provider, sadly I can't fix it
