### ISSUE TITLE
cover.jpg in wrong folder

### ISSUE THREAD

**Issue by mHaisham** [MakeYourLifeEasier/novel-ebook.com#47]
cover.jpg should be in the outer most folder where it would be a sibling to OEBPS,

Unlike its current position which is inside OEBPS

**Comment by MichaelGuardian** [comment]
Yea I think there was some old code I reused that had this path hardcoded. If I recall correctly having is the correct way according to the spec but the path to the cover is also specified in the toc file.

Did you run into any issues seeing the cover on any devices? Will likely put the cover in the root directory, just curious

**Comment by mHaisham** [comment]
i was using `freda` to read a novel on windows. the cover image was not displayed so i experimented by putting the cover.jpg on the root and that seemed to fix it.

I later tried reading on my phone using `readEra` where it doesnt seem to show the cover image, so as things stand im quite confused.

**Comment by MichaelGuardian** [comment]
Hm, readEra shows the cover correctly in my case. I'll change the cover location anyway to be spec conform in a later update.

**Comment by mHaisham** [comment]
Cover shows on both **freda** and **readEra**
