### ISSUE TITLE
Pop up redirecting to malicious websites 

### ISSUE THREAD

**Issue by georgej99** [MakeYourLifeEasier/novel-ebook.com#48]
Pop ups redirecting to malicious websites.
Please look into this.

Note : These pop ups shows up at random when click on web page and doesn't require request for downloading novel.

**Comment by MichaelGuardian** [comment]
Yes, I've been experimenting with ads since the patreon account got suspended. I've also been closely monitoring the ads that get played out. They'll likely get removed after I find some other way to pay for the hardware

**Comment by georgej99** [comment]
Cool. Why don't you try google ads is better or is there some copyright issues?

**Comment by MichaelGuardian** [comment]
Google doesn't like single page applications and can't correctly parse the content, so the bot doesn't verify the site

**Comment by georgej99** [comment]
That sucks. Hope things workout. 
All the best!
