### ISSUE TITLE
Unable to select chapters (start) - (end)

### ISSUE THREAD

**Issue by NIGHT49** [MakeYourLifeEasier/novel-ebook.com#51]
i am unable to select the beginning or ending chapter on any books (time: 10:10pm - 10:29) (Date: 26/08/2020)

1.go to site
2.select book
3.click on the choose starting/ending chapter
4.but it dose nothing

**Expected behavior**
well i expected to select chapters

![Screenshot_2020-08-26 Novel-Ebook](https://user-images.githubusercontent.com/70270646/91303790-dda30280-e7eb-11ea-876d-226ea6ef752c.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [fire fox]
 - Version [79.0 (64-bit)]

**Additional context**
was working when i used it on sunday 23rd Aug

**Comment by MichaelGuardian** [comment]
Fixed

**Comment by NIGHT49** [comment]
Thank you for addressing the issue and taking the time to respond.
