### ISSUE TITLE
Incomplete chapter in the selection of Trash of the Count

### ISSUE THREAD

**Issue by markilagan** [MakeYourLifeEasier/novel-ebook.com#53]
**Describe the bug**
Incomplete chapter in the selection of Trash of the Count’s Family only get 1 - 79

**To Reproduce**
1. Go to 'https://novel-ebook.com/#'
2. Click on search the type Trash of the Count’s Family and click the choose ending chapter its up to 79 only where to find the other chapter

**Screenshots**

![image](https://user-images.githubusercontent.com/70561265/91816144-8081d380-ec67-11ea-9d04-1db32ad8c0cc.png)

**Comment by MichaelGuardian** [comment]
#44
