### ISSUE TITLE
No file is being downloaded

### ISSUE THREAD

**Issue by aki-77** [MakeYourLifeEasier/novel-ebook.com#55]
![Screenshot_20200908_200712](https://user-images.githubusercontent.com/68814576/92490879-2d7fc180-f20f-11ea-88bf-12f0278d2adb.jpg)

**Comment by aki-77** [comment]
I did wait for it to download the file for 15 minutes

**Comment by aki-77** [comment]
I tried downloading it on pc and mobile and also tried downloading it on different browsers also

**Comment by MichaelGuardian** [comment]
This issue seems to come from this particular novel missing the cover.  I'll look into it.

**Comment by aki-77** [comment]
Yeah i taught so there are many novels like this with missing covers

**Comment by MichaelGuardian** [comment]
Fixed

**Comment by aki-77** [comment]
Not fixed the issue is still there

**Comment by MichaelGuardian** [comment]
I've fixed the bug that resulted in missing covers on some novels.
