### ISSUE TITLE
Now there are no chapters available on "I reincarnated as a stick"

### ISSUE THREAD

**Issue by aki-77** [MakeYourLifeEasier/novel-ebook.com#56]
**Describe the bug**

**To Reproduce**
1. Go to 'https://novel-ebook.com/'
2. Click on 'i reincarnated as a stick'
3. Scroll down to 'end chapter'
Now there are no chapters persent
![Screenshot_20200908_203545](https://user-images.githubusercontent.com/68814576/92494097-e72c6180-f212-11ea-81d7-8e3ee6affe6a.jpg)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MichaelGuardian** [comment]
This is not a bug on my end but on the source website. Can't do anything about it.
