### ISSUE TITLE
"Starting Chapter is greater than Ending Chapter" when it is not.

### ISSUE THREAD

**Issue by Mihoshika** [MakeYourLifeEasier/novel-ebook.com#59]
Tried downloading chapters 99-110 of Martial World. Starting chapter is 99, End chapter is 110. Seems to be an with recognizing what is actually the digits of a number. I.e. 9-10 doesn't work, nor does 2-50. 9-95 works, as 95 starts w/ 9. I'm assuming the space after it or something is being considered a number greater than 9, thus making it give the wrong order.

**Comment by MichaelGuardian** [comment]
Fixed.
