### ISSUE TITLE
Didn't find Stop, Friendly fire from WuxiaWorld? 

### ISSUE THREAD

**Issue by Kanigami** [MakeYourLifeEasier/novel-ebook.com#6]
As the title says I tried looking for it but it wasn't there, and I have no idea why (https://www.wuxiaworld.com/novel/stop-friendly-fire for ref), can you help me?
Thx ^^

**Comment by MichaelGuardian** [comment]
Well, you didn't find it because it wasn't there :D 
Book should be available now.
