### ISSUE TITLE
Malware in site script

### ISSUE THREAD

**Issue by that1cat** [MakeYourLifeEasier/novel-ebook.com#61]
Using a Kindle (they run on android os) in Firefox Focus, Silk, and Firefox without uBlock Origin running, upon tapping the search box, I'll get redirected to a bad site. (Ie "you've won a free ipad" kind.)

It stems from the iclickcdn which you can see towards the top of the page source code. Here's a link about it: https://www.getastra.com/blog/cms/wordpress-security/fix-push-notifications-malware/

**Comment by MichaelGuardian** [comment]
This is not malware, it's called bad ads. I'm monitoring the ads played out on the site and am aware of the bad ads that are getting displayed. I'm looking for alternative monetization but even with these ads I'm not even able to cover server cost
