### ISSUE TITLE
error2

### ISSUE THREAD

**Issue by that1cat** [MakeYourLifeEasier/novel-ebook.com#62]
Using a Kindle (running on android os) in firefox and silk (default browser) upon trying to create an epub of Card Room, it won't work and will only give an "error2" message. In firefox this immediately pops up, while in silk it'll grab the chapters (I used 1-150 though I did try a few other 1-mid 100's as well) and at the end (150) the error pops up.

**Comment by MichaelGuardian** [comment]
Error 2 shouldn't be a browser problem. I've just checked and Card Room seems to work. 
Could you try again and see if it works? Don't have a fire tablet to test.
