### ISSUE TITLE
incorrect epub format error after download

### ISSUE THREAD

**Issue by foodfan93** [MakeYourLifeEasier/novel-ebook.com#65]
downloaded kuma kuma kuma bear ch1-354 on iphone. opened the file through apple’s ‘Books’ app and got an error saying: “it is formatted incorrectly or is in a format that apples Books cannot open’.

this is not my first time using this website or downloading epubs from other places. i usually only read epubs on my iphone xr, nowhere else. 

i have just checked if im getting this issue for other novels, but i am not (downloaded and was able to read “only i level up”).

**Comment by MichaelGuardian** [comment]
Did you try it with a different chapter range and/or with a different browser?
