### ISSUE TITLE
City of Sin (repeated chapter)

### ISSUE THREAD

**Issue by cynex8089** [MakeYourLifeEasier/novel-ebook.com#68]
In "City of Sin"  no matter the range of chapters I chose, it always only shows last selected chapter round and round in downloaded epub file

1. Click on "City of Sin"
2. Select any range of chapters (for eg chapter 1 to 100 )
3. Click on download
4. Download the File.

**Expected behavior**
On opening the epub only last chapter (i.e.100) will be seen in place of each and every chapter (i.e. 100 times)

**Smartphone (please complete the following information):**
 - Device: Redmi 3S prime
 - OS: Android 6.1 Marshmallow
 - Browser:  Chrome (v84.0.4147.111)
                     Microsoft Edge (v45.06.4.5043)

**Comment by MichaelGuardian** [comment]
Fixed
