### ISSUE TITLE
Advent of the Archmage (Struck at Processing)

### ISSUE THREAD

**Issue by cynex8089** [MakeYourLifeEasier/novel-ebook.com#69]
Advent of the Archmage it doesn't go forward after "Processing request. Please wait"

1. Go to Advent of the Archmage
2. Click on Chapter 1
3. Scroll down to last Chapter
4. Click Download

**Expected behavior**
After clicking download button it will show "Processing request, Please wait" and will not go any further than that

**Screenshots**
![Screenshot_2020-10-04-00-22-08-736_com microsoft emmx](https://user-images.githubusercontent.com/72317184/94999704-d3d5a180-05d8-11eb-8b3d-ee022554ffd9.png)

*

**Smartphone (please complete the following information):**
 - Device: Redmi 3S prime
 - OS: Android 6.1 Marshmallow
 - Browser: Chrome (v84.0.4147.111)
                    Microsoft Edge (v45.06.4.5043)

**Additional context**
Site is not struck, i can close the window if i want to, or choose different chapters

**Comment by MichaelGuardian** [comment]
If identified the bug and will fix it in the next release. For now you can try downloading less then 50 chapters at a time.

**Comment by MichaelGuardian** [comment]
Fixed
