### ISSUE TITLE
repeated chapters

### ISSUE THREAD

**Issue by centpede** [MakeYourLifeEasier/novel-ebook.com#70]
**Describe the bug**
continued chapters of supreme magus is repeated 
For eg. ch 57 a new lesson has the same text as ch 58 a new lesson (2)
This is continued in all chapters that are continued 
**To Reproduce**
1. Go to 'supreme magus'
2. Click on 'select chapter and download '
3. Scroll down to 'chapter 57'

**Expected behavior**
repeated chapter.

**Desktop (please complete the following information):**
 - OS: [Win 10 (2004)]
 - Browser [chrome]

**Comment by MichaelGuardian** [comment]
#44 Can't fix order for now
