### ISSUE TITLE
Desolate Era - mixed chapters

### ISSUE THREAD

**Issue by chosen1234** [MakeYourLifeEasier/novel-ebook.com#71]
Hi,

I tried to download the `Desolate Era` with all chapters in an epub. The process went smoothly, but the chapters are all mixed.

For example, all chapters 1 from each book are coming one after another. ( see attached screenshot)
![Screenshot 2020-10-05 at 09 32 15](https://user-images.githubusercontent.com/17879090/95051690-f1e0f600-06ed-11eb-9992-1a0118fe2218.png)

Thanks,
Alex

PS: thank you for a great project

**Comment by chosen1234** [comment]
Same thing happens with demon hunter

**Comment by MichaelGuardian** [comment]
#44 Can't fix order for now
