### ISSUE TITLE
Divine Throne of Primordial Blood Chapter sequence wrong

### ISSUE THREAD

**Issue by Byakorit** [MakeYourLifeEasier/novel-ebook.com#72]
**Describe the bug**
The chapters of the novel Divine Throne of Primordial Blood are arranged incorrectly. 

**To Reproduce**
1. Go to Divine Throne of Primordial Blood
2. Click on Starting Chapter
3. Scroll down to 2 chapters

**Expected behavior**
The chapter list will show the chapters not arranged in the correct order. With the exception of Book 6 and Book 7.

**Screenshots**
![Screenshot_20201009-023154](https://user-images.githubusercontent.com/72572297/95551257-00f0dc80-0a3d-11eb-9d7e-17f9d6421c64.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: LDN-LX2 8.0.0.158(C636) 
 - OS: Android 8.0.0
 - Browser Chrome 83.0.4103. 106
 - Version 83.0.4103. 106

**Additional context**

**Comment by MichaelGuardian** [comment]
The sorting issue is a known issue #44
