### ISSUE TITLE
Talisman Emperor epub has several issues

### ISSUE THREAD

**Issue by becool1960** [MakeYourLifeEasier/novel-ebook.com#75]
Chapters shown in the start and end menu before the epub is generated are in the wrong order. The epilogue chapters are not at the end of the chapter list. For example:
Chapter 1
Epilogue 1
Chapter 2
Epilogue 2
...

After an epub is generated, the chapters are also generated in the same incorrect chapter order.

When generated, multi part chapters repeat the last part for all the parts. For example:

Chapter xxx part 1/5
...

would contain part 5/5 for parts 1 to 5.

The epilogue chapters are multi part and they seem to affect the chapter before it. For example:

Chapter 1
Epilogue 1 part 1/3
...

Also causes Chapter 1 to contain Epilogue 1 part 3/3.

All other single part chapters seem to be generated correctly.

**Comment by MichaelGuardian** [comment]
The sorting issue is a known issue #44
