### ISSUE TITLE
Unable to download webnovel The Silly Alchemist

### ISSUE THREAD

**Issue by Bhagesh2208** [MakeYourLifeEasier/novel-ebook.com#78]
**Describe the bug**
After trying to download webnovel The Silly Alchemist this message appears. There seems to be a problem with this novel, Try after 7 days. Its already been more than 7 days.

**To Reproduce**
1. Go to 'www.novel-ebook.com'
2. Click on 'The Silly Alchemist'
3. Scroll down to 'chapter 1 to chapter 771'
4. There is a problem with this novel

**Expected behavior**
Novel should start downloading.

**Screenshots**
![Screenshot_20201102-154951](https://user-images.githubusercontent.com/70843231/97858854-c6b9e880-1d25-11eb-8f3f-7f3f73e7660c.jpeg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Resmi Note 5 Pro, Lenovo Tab M10]
 - OS: [9]
 - Browser [Google Chrome]
 - Version [86.0.04240.110]

**Additional context**

**Comment by MichaelGuardian** [comment]
Fixed
