### ISSUE TITLE
Missing final "t" in chapter names, corrupted chapter

### ISSUE THREAD

**Issue by rdragonrydr** [MakeYourLifeEasier/novel-ebook.com#8]
I have found two bugs.
The easiest to reproduce is that every chapter name that ends in a "t" has the "t" removed.

The second is that chapter 235 of The Legendary Mechanic has lost all formatting, and partial HTML formatting marks litter the chapter (probably related, but I don't know the root cause). I'm not sure if this one is on your end, since several other chapters in that story are also weird -- one had the Chinese characters still present, and a few others were apparently down for editing at the time that the story was archived.

I'm using the most recent Chromium (NOT Chrome; the open-source one) on Ubuntu 18.04.

If I can also add a feature request, I'd love to see the following stories added:
https://www.webnovel.com/book/11418908406358805/Black-Tech-Internet-Cafe-System
https://www.webnovel.com/book/13071505405554605/Legend-of-the-Mythological-Genes

**Comment by MichaelGuardian** [comment]
Thanks for the feedback!

Both stories have been added. As for the other two bugs you've reported, both are related to the thrid-party hosting the chapter content so they can't fix the bugs directly. If I have time I look into some kind of hotfix that resolves the "t" bug.

**Comment by theonlygusti** [comment]
I had this bug from Rebirth of the Thief Who Roamed the World, the final character of the chapter title would be normal body text in its own paragraph above the chapter content.
