### ISSUE TITLE
Record human emperor file blank

### ISSUE THREAD

**Issue by kirakira12id** [MakeYourLifeEasier/novel-ebook.com#86]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here
Open file after downloading ,blank for chapter 1-1500+
![Screenshot_2020-11-23-09-30-44-603_com flyersoft moonreader](https://user-images.githubusercontent.com/74886422/99924927-a8686b00-2d6e-11eb-8836-6733fa0b9c67.png)

**Comment by MichaelGuardian** [comment]
Fixed. Now under a different name
