### ISSUE TITLE
The Oracle Paths 

### ISSUE THREAD

**Issue by Nugget-Lord** [MakeYourLifeEasier/novel-ebook.com#91]
**Describe the bug**
The novel "The Oracle Paths" is missing its cover and shows no downloadable chapters

**To Reproduce**
Pretty simple
go to the site "Novel-Ebook"
type "The Oracle Paths" into the search bar
click on "The Oracle Paths"

**Expected behavior**
I expected to see the cover for the novel and to be able to download chapters

**Screenshots**
![NovelEbook](https://user-images.githubusercontent.com/75463403/101119388-12b7b180-35a0-11eb-9d66-ac5be7d6730c.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 pro]
 - Browser [Opra]
 - Version [idk]

**Comment by MichaelGuardian** [comment]
While it's missing it's cover, downloadable chapters available. Maybe try a different browser.
