### ISSUE TITLE
God of Fishing: missing chapters

### ISSUE THREAD

**Issue by Oakwooooood** [MakeYourLifeEasier/novel-ebook.com#96]
**Describe the bug**
On novel-ebook.com the last chapter you can find is 322 but I see that on www.webnovel.com, www.wuxiaworld.co www.readlightnovel.org, https://boxnovel.com or https://readnovelfull.com the current last chapter is 499. Maybe those sites are not supported by your webapp ? Is there any way to get an ebook that goes to the current last translated chapter ? Thank you!

**To reproduce**
1. Go to God of Fishing page
2. Click on "choose ending chapter"
3. Scroll down to last available chapter

**Expected behavior**
The last available chapter is 322 instead of 499.

**Comment by MichaelGuardian** [comment]
#44 . Currently I'm a little busy and don't have time nor resources to add new sources. Sadly I can't do anything about this atm.
